config/routes.rb
Rails.application.routes.draw do
  resources :maps do
    resources :segments
  end

  get  "maps/:id/routing", to: "maps#start_routing", as: :start_routing
  post "maps/:id/routing", to: "maps#do_routing", as: :do_routing

  root to: 'maps#index'
end

app/models/map.rb
# Represents a custom map, which will have segments/steps/nodes
class Map < ActiveRecord::Base
  has_many :segments
end

app/controllers/maps_controller.rb
# By this controller you can get routes from a map.
class MapsController < ApplicationController
  #include Roar::Rails::ControllerAdditions
  #include Roar::Rails::ControllerAdditions::Render
  # Comments above was a try to use ROAR in order to get HATEOAS behavior.
  # The goal was to make resources 'discoverable'
  # Got some problems and couldn't get it to work in time.

  before_action :set_map, only: [:show, :edit, :update, :destroy, :start_routing, :do_routing]

  # Should have splited routing in another controller/resource.
  # It would give me more flexibility and would make this controller
  # less bloated
  def start_routing
    @starting_points = @map.segments.map{|s| [s.source, s.source]}
    @destination_points = @map.segments.map{|s| [s.destination, s.destination]}
  end

  def do_routing
    # Only responds to html/template. 
    # Got stack overflow when serializing as json. Looks like some problem with
    # the serializers, once it doesn't occur with the same model anywhere.
    @routing_info = Router.route(@map, build_routing_info(params))
  end 

  def index
    @maps = Map.all
  end

  def show
  end

  def new
    @map = Map.new
  end

  def edit
  end

  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:name)
    end

    def build_routing_info(params)
      params.slice(:from, :to, :fuel_consumption, :fuel_price)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/do_routing.html.erb
<table>
  <thead>
    <tr>
      <th>Path</th>
      <th>Distance</th>
      <th>Cost</th>
    </tr>
  </thead>

  <tbody>
    <tr>
        <td><%= @routing_info.route %></td>
        <td><%= @routing_info.route.distance %></td>
        <td><%= @routing_info.cost %></td>
    </tr>
  </tbody>

</table>
<%= link_to 'Back', start_routing_path %> |
<%= link_to 'Maps', maps_path %>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Maps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Route</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= map.name %></td>
        <td><%= link_to 'Segments', map_segments_path(map) %></td>
        <td><%= link_to 'Route to...', start_routing_path(map) %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @map.name %>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>

app/views/maps/start_routing.html.erb
<%=form_tag start_routing_path(@map) do %>
  <div class="field">
    <%=select_tag :from, options_for_select(@starting_points) %>
    <%=label_tag 'From' %>
  </div>

  <div class="field">
    <%=select_tag :to, options_for_select(@destination_points) %>
    <%=label_tag 'To' %>
  </div>  

  <div class="field">
    <%=text_field_tag 'fuel_consumption'%>
    <%=label_tag 'Fuel consumption' %>
  </div>

  <div class="field">
    <%=text_field_tag 'fuel_price'%>
    <%=label_tag 'Fuel price' %>
  </div>

  <div class="actions">
    <%= submit_tag "Route" %>
  </div>  
  
  <%= link_to 'Back', maps_path %>
<% end%>