config/routes.rb
Rails.application.routes.draw do
  resources :maps do
    resources :segments
  end

  get  "maps/:id/routing", to: "maps#start_routing", as: :start_routing
  post "maps/:id/routing", to: "maps#do_routing", as: :do_routing

  root to: 'maps#index'
end

app/models/segment.rb
# Represents a connection between a source and a destination
class Segment < ActiveRecord::Base
  belongs_to :map
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_action :set_segment, only: [:show, :edit, :update, :destroy]

  # GET /segments
  # GET /segments.json
  def index
    @map = Map.where(id: params[:map_id]).first
    @segments = Segment.all
  end

  # GET /segments/1
  # GET /segments/1.json
  def show
  end

  # GET /segments/new
  def new
    @map = Map.where(id: params[:map_id]).first
    @segment = Segment.new
  end

  # GET /segments/1/edit
  def edit
    @map = Map.where(id: params[:map_id]).first
  end

  # POST /segments
  # POST /segments.json
  def create
    @segment = Segment.new(segment_params)

    respond_to do |format|
      if @segment.save
        format.html { redirect_to map_segment_path(@segment.map, @segment), notice: 'Segment was successfully created.' }
        format.json { render :show, status: :created, location: @segment }
      else
        format.html { render :new }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segments/1
  # PATCH/PUT /segments/1.json
  def update
    respond_to do |format|
      if @segment.update(segment_params)
        format.html { redirect_to map_segment_path(@segment.map, @segment), notice: 'Segment was successfully updated.' }
        format.json { render :show, status: :ok, location: @segment }
      else
        format.html { render :edit }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.json
  def destroy
    @segment.destroy
    respond_to do |format|
      format.html { redirect_to map_segments_url, notice: 'Segment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segment
      @segment = Segment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segment_params
      params.require(:segment).permit(:source, :destination, :distance, :map_id)
    end
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_form.html.erb
<%= form_for([@map, @segment]) do |f| %>
  <% if @segment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

      <ul>
      <% @segment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.text_field :distance %>
  </div>

  <%= f.hidden_field :map_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/segments/edit.html.erb
<h1>Editing Segment</h1>

<%= render 'form' %>

<%= link_to 'Show', map_segment_path(@segment.map, @segment) %> |
<%= link_to 'Back', map_segments_path %>

app/views/segments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Segments</h1>

<table>
  <thead>
    <tr>
      <th>Source</th>
      <th>Destination</th>
      <th>Distance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @segments.each do |segment| %>
      <tr>
        <td><%= segment.source %></td>
        <td><%= segment.destination %></td>
        <td><%= segment.distance %></td>
        <td><%= link_to 'Show', map_segment_path(segment.map, segment) %></td>
        <td><%= link_to 'Edit', edit_map_segment_path(segment.map, segment) %></td>
        <td><%= link_to 'Destroy', map_segment_path(segment.map, segment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Segment', new_map_segment_path %> |
<%= link_to 'Maps', maps_path %>

app/views/segments/new.html.erb
<h1>New Segment</h1>

<%= render 'form' %>

<%= link_to 'Back', map_segments_path %>

app/views/segments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source:</strong>
  <%= @segment.source %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @segment.destination %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @segment.distance %>
</p>

<%= link_to 'Edit', edit_map_segment_path(@segment.map, @segment) %> |
<%= link_to 'Back', map_segments_path %> |
<%= link_to 'Maps', maps_path %>